import {
  Employee,
  OfferLetter,
  ExperienceLetter,
  LOR,
  SalaryDataPoint,
  DepartmentSalary,
  HiringTrend,
  ActivityItem,
  Template,
} from '@/types';

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'EMP001',
    employeeId: 'EMP001',
    name: 'Priya Sharma',
    email: 'priya.sharma@collegesimplified.in',
    role: 'Senior Software Engineer',
    department: 'Engineering',
    salary: 180000,
    joiningDate: '2022-03-15',
    status: 'Active',
  },
  {
    id: 'EMP002',
    employeeId: 'EMP002',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@collegesimplified.in',
    role: 'Product Designer',
    department: 'Design',
    salary: 150000,
    joiningDate: '2021-07-01',
    status: 'Active',
  },
  {
    id: 'EMP003',
    employeeId: 'EMP003',
    name: 'Ananya Singh',
    email: 'ananya.singh@collegesimplified.in',
    role: 'Marketing Manager',
    department: 'Marketing',
    salary: 130000,
    joiningDate: '2020-11-20',
    status: 'Active',
  },
  {
    id: 'EMP004',
    employeeId: 'EMP004',
    name: 'Vikram Patel',
    email: 'vikram.patel@collegesimplified.in',
    role: 'Sales Executive',
    department: 'Sales',
    salary: 95000,
    joiningDate: '2023-01-10',
    status: 'Active',
  },
  {
    id: 'EMP005',
    employeeId: 'EMP005',
    name: 'Sneha Iyer',
    email: 'sneha.iyer@collegesimplified.in',
    role: 'HR Manager',
    department: 'HR',
    salary: 120000,
    joiningDate: '2021-04-05',
    status: 'Active',
  },
  {
    id: 'EMP006',
    employeeId: 'EMP006',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@collegesimplified.in',
    role: 'Financial Analyst',
    department: 'Finance',
    salary: 140000,
    joiningDate: '2022-08-22',
    status: 'Active',
  },
  {
    id: 'EMP007',
    employeeId: 'EMP007',
    name: 'Neha Gupta',
    email: 'neha.gupta@collegesimplified.in',
    role: 'Full Stack Developer',
    department: 'Engineering',
    salary: 160000,
    joiningDate: '2023-03-01',
    status: 'Active',
  },
  {
    id: 'EMP008',
    employeeId: 'EMP008',
    name: 'Ravi Kumar',
    email: 'ravi.kumar@collegesimplified.in',
    role: 'Operations Lead',
    department: 'Operations',
    salary: 115000,
    joiningDate: '2020-06-15',
    status: 'Inactive',
  },
  {
    id: 'EMP009',
    employeeId: 'EMP009',
    name: 'Deepika Nair',
    email: 'deepika.nair@collegesimplified.in',
    role: 'Product Manager',
    department: 'Product',
    salary: 190000,
    joiningDate: '2021-09-10',
    status: 'Active',
  },
  {
    id: 'EMP010',
    employeeId: 'EMP010',
    name: 'Aditya Verma',
    email: 'aditya.verma@collegesimplified.in',
    role: 'DevOps Engineer',
    department: 'Engineering',
    salary: 170000,
    joiningDate: '2022-12-01',
    status: 'On Leave',
  },
  {
    id: 'EMP011',
    employeeId: 'EMP011',
    name: 'Pooja Reddy',
    email: 'pooja.reddy@collegesimplified.in',
    role: 'UI/UX Designer',
    department: 'Design',
    salary: 135000,
    joiningDate: '2023-05-15',
    status: 'Active',
  },
  {
    id: 'EMP012',
    employeeId: 'EMP012',
    name: 'Suresh Joshi',
    email: 'suresh.joshi@collegesimplified.in',
    role: 'Backend Developer',
    department: 'Engineering',
    salary: 155000,
    joiningDate: '2022-01-20',
    status: 'Active',
  },
  {
    id: 'EMP013',
    employeeId: 'EMP013',
    name: 'Kavita Pillai',
    email: 'kavita.pillai@collegesimplified.in',
    role: 'Content Strategist',
    department: 'Marketing',
    salary: 90000,
    joiningDate: '2023-07-01',
    status: 'Active',
  },
  {
    id: 'EMP014',
    employeeId: 'EMP014',
    name: 'Manish Thakur',
    email: 'manish.thakur@collegesimplified.in',
    role: 'Sales Manager',
    department: 'Sales',
    salary: 125000,
    joiningDate: '2021-02-14',
    status: 'Active',
  },
  {
    id: 'EMP015',
    employeeId: 'EMP015',
    name: 'Asha Choudhary',
    email: 'asha.choudhary@collegesimplified.in',
    role: 'Data Analyst',
    department: 'Finance',
    salary: 110000,
    joiningDate: '2022-06-30',
    status: 'Active',
  },
];

export const MOCK_OFFER_LETTERS: OfferLetter[] = [
  {
    id: 'OL001',
    employeeId: 'EMP007',
    employeeName: 'Neha Gupta',
    templateName: 'Standard Offer Letter',
    generatedAt: '2023-02-28T10:00:00Z',
    sentAt: '2023-02-28T10:30:00Z',
    status: 'Sent',
  },
  {
    id: 'OL002',
    employeeId: 'EMP010',
    employeeName: 'Aditya Verma',
    templateName: 'Senior Engineer Offer',
    generatedAt: '2022-11-28T09:00:00Z',
    sentAt: '2022-11-28T09:15:00Z',
    status: 'Sent',
  },
  {
    id: 'OL003',
    employeeId: 'EMP011',
    employeeName: 'Pooja Reddy',
    templateName: 'Design Role Offer',
    generatedAt: '2023-05-12T14:00:00Z',
    sentAt: '2023-05-12T14:30:00Z',
    status: 'Sent',
  },
  {
    id: 'OL004',
    employeeId: 'EMP013',
    employeeName: 'Kavita Pillai',
    templateName: 'Standard Offer Letter',
    generatedAt: '2023-06-28T11:00:00Z',
    status: 'Generated',
  },
  {
    id: 'OL005',
    employeeId: 'EMP015',
    employeeName: 'Asha Choudhary',
    templateName: 'Finance Role Offer',
    generatedAt: '2022-06-25T15:00:00Z',
    sentAt: '2022-06-25T16:00:00Z',
    status: 'Sent',
  },
];

export const MOCK_EXPERIENCE_LETTERS: ExperienceLetter[] = [
  {
    id: 'EL001',
    employeeId: 'EMP008',
    employeeName: 'Ravi Kumar',
    joiningDate: '2020-06-15',
    relievingDate: '2024-12-31',
    duration: '4 years, 6 months',
    generatedAt: '2025-01-05T10:00:00Z',
    status: 'Sent',
  },
  {
    id: 'EL002',
    employeeId: 'EMP004',
    employeeName: 'Vikram Patel',
    joiningDate: '2023-01-10',
    relievingDate: '2024-08-31',
    duration: '1 year, 8 months',
    generatedAt: '2024-09-02T09:00:00Z',
    status: 'Generated',
  },
];

export const MOCK_LORS: LOR[] = [
  {
    id: 'LOR001',
    employeeId: 'EMP001',
    employeeName: 'Priya Sharma',
    recipientName: 'Harvard Business School',
    recipientOrg: 'Harvard University',
    recommendation:
      'Priya has consistently demonstrated exceptional technical leadership and problem-solving skills...',
    generatedAt: '2025-02-10T10:00:00Z',
    status: 'Sent',
  },
  {
    id: 'LOR002',
    employeeId: 'EMP009',
    employeeName: 'Deepika Nair',
    recipientName: 'Stanford GSB',
    recipientOrg: 'Stanford University',
    recommendation:
      'Deepika has shown outstanding product vision and cross-functional leadership capabilities...',
    generatedAt: '2025-03-15T11:00:00Z',
    status: 'Generated',
  },
];

export const MOCK_SALARY_DATA: SalaryDataPoint[] = [
  { month: 'Jan', expenditure: 1850000, headcount: 12 },
  { month: 'Feb', expenditure: 1920000, headcount: 13 },
  { month: 'Mar', expenditure: 2100000, headcount: 14 },
  { month: 'Apr', expenditure: 2050000, headcount: 14 },
  { month: 'May', expenditure: 2200000, headcount: 15 },
  { month: 'Jun', expenditure: 2350000, headcount: 15 },
  { month: 'Jul', expenditure: 2280000, headcount: 15 },
  { month: 'Aug', expenditure: 2400000, headcount: 15 },
  { month: 'Sep', expenditure: 2520000, headcount: 15 },
  { month: 'Oct', expenditure: 2480000, headcount: 15 },
  { month: 'Nov', expenditure: 2600000, headcount: 15 },
  { month: 'Dec', expenditure: 2750000, headcount: 15 },
];

export const MOCK_DEPT_SALARIES: DepartmentSalary[] = [
  { department: 'Engineering', totalSalary: 665000, headcount: 4, avgSalary: 166250 },
  { department: 'Design', totalSalary: 285000, headcount: 2, avgSalary: 142500 },
  { department: 'Marketing', totalSalary: 220000, headcount: 2, avgSalary: 110000 },
  { department: 'Sales', totalSalary: 220000, headcount: 2, avgSalary: 110000 },
  { department: 'HR', totalSalary: 120000, headcount: 1, avgSalary: 120000 },
  { department: 'Finance', totalSalary: 250000, headcount: 2, avgSalary: 125000 },
  { department: 'Operations', totalSalary: 115000, headcount: 1, avgSalary: 115000 },
  { department: 'Product', totalSalary: 190000, headcount: 1, avgSalary: 190000 },
];

export const MOCK_HIRING_TRENDS: HiringTrend[] = [
  { month: 'Jan', hired: 2, left: 0 },
  { month: 'Feb', hired: 1, left: 0 },
  { month: 'Mar', hired: 3, left: 1 },
  { month: 'Apr', hired: 0, left: 0 },
  { month: 'May', hired: 2, left: 0 },
  { month: 'Jun', hired: 1, left: 1 },
  { month: 'Jul', hired: 0, left: 0 },
  { month: 'Aug', hired: 2, left: 0 },
  { month: 'Sep', hired: 1, left: 0 },
  { month: 'Oct', hired: 0, left: 1 },
  { month: 'Nov', hired: 3, left: 0 },
  { month: 'Dec', hired: 0, left: 0 },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: 'ACT001',
    type: 'employee_added',
    title: 'New employee added',
    subtitle: 'Kavita Pillai joined Marketing',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'ACT002',
    type: 'offer_sent',
    title: 'Offer letter sent',
    subtitle: 'Sent to Pooja Reddy via email',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'ACT003',
    type: 'letter_generated',
    title: 'Experience letter generated',
    subtitle: 'For Vikram Patel',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 'ACT004',
    type: 'email_sent',
    title: 'Bulk email sent',
    subtitle: 'Salary slip sent to 15 employees',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: 'ACT005',
    type: 'offer_sent',
    title: 'LOR generated',
    subtitle: 'Recommendation for Priya Sharma',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 'tpl-growth-intern',
    name: 'Growth Intern',
    type: 'offer',
    description: 'Market research, campaign execution, social media, growth strategies',
  },
  {
    id: 'tpl-software-dev-intern',
    name: 'Software Development Intern',
    type: 'offer',
    description: 'Feature development, code reviews, bug fixes, CI/CD, documentation',
  },
  {
    id: 'tpl-graphic-design-intern',
    name: 'Graphic Design Intern',
    type: 'offer',
    description: 'Visual assets, brand guidelines, UI mockups, social media graphics',
  },
  {
    id: 'tpl-content-writing-intern',
    name: 'Content Writing Intern',
    type: 'offer',
    description: 'Blog posts, copywriting, SEO content, proofreading, social media copy',
  },
  {
    id: 'tpl-hr-intern',
    name: 'Human Resources Intern',
    type: 'offer',
    description: 'Recruitment, onboarding, employee records, HR initiatives',
  },
  {
    id: 'tpl-marketing-intern',
    name: 'Marketing Intern',
    type: 'offer',
    description: 'Campaign management, analytics, email marketing, market research',
  },
  {
    id: 'tpl-social-media-intern',
    name: 'Social Media Intern',
    type: 'offer',
    description: 'Platform management, content scheduling, community engagement, influencer outreach',
  },
  {
    id: 'tpl-data-analyst-intern',
    name: 'Data Analyst Intern',
    type: 'offer',
    description: 'Data collection, report generation, dashboards, SQL, statistical analysis',
  },
  {
    id: 'TPL005',
    name: 'Standard Experience Certificate',
    type: 'experience',
    description: 'Official experience certificate with tenure details',
  },
  {
    id: 'TPL006',
    name: 'LOR Academic',
    type: 'lor',
    description: 'Academic recommendation letter template',
  },
  {
    id: 'TPL007',
    name: 'LOR Professional',
    type: 'lor',
    description: 'Professional recommendation for job applications',
  },
];
